export interface StateInfo {
  slug: string;
  name: string;
  abbreviation: string;
  terrain: string;
  classSystem: boolean;
  licenseRequired: boolean;
  helmetRequired: string;
  maxSpeed: string;
  maxWattage: string;
  bikePaths: string;
  lawSummary: string;
  ridingTips: string[];
  topCities: string[];
  metaDescription: string;
  intro: string;
}

export const STATES: StateInfo[] = [
  {
    slug: 'california',
    name: 'California',
    abbreviation: 'CA',
    terrain: 'Diverse: flat coastal cities, steep hills in San Francisco, mountain trails inland',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 18. Class 3 riders under 18 must wear a helmet.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on bike paths. Class 3 restricted to roads and bike lanes.',
    lawSummary: 'California was the first state to adopt the three-class e-bike system. As of 2026, all new e-bikes sold or rented must comply with UL 2849 safety certification. No license, registration, or insurance required. E-bikes must have a rear red reflector or taillight.',
    ridingTips: [
      'San Francisco hills demand a mid-drive motor with 60+ Nm torque',
      'Coastal fog and moisture mean fenders and integrated lights are essential',
      'Many California cities offer e-bike purchase rebates, so check local incentive programs before buying',
      'The California Coastal Trail offers hundreds of miles of scenic e-bike riding',
    ],
    topCities: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'Santa Monica'],
    metaDescription: 'Find the best electric bikes for riding in California. State e-bike laws, top picks for CA terrain, and where to buy.',
    intro: 'California leads the nation in e-bike adoption, with strong cycling infrastructure, purchase incentive programs, and year-round riding weather. Whether you are commuting through LA traffic, climbing San Francisco hills, or cruising the Pacific coast, there is an e-bike that fits.',
  },
  {
    slug: 'texas',
    name: 'Texas',
    abbreviation: 'TX',
    terrain: 'Mostly flat with gentle rolling hills. Hot summers make pedal-assist essential.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state helmet requirement for adults',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1, 2, and 3 allowed on roads. Local jurisdictions control bike path access.',
    lawSummary: 'Texas adopted the three-class system in 2019. E-bikes are treated as bicycles. No license, registration, or insurance required. Riders have the same rights and duties as cyclists. Local cities can set their own rules for trails and paths.',
    ridingTips: [
      'Texas heat makes throttle-equipped (Class 2) bikes popular so you can take a break from pedaling',
      'Flat terrain means you can prioritize range over torque',
      'Austin and San Antonio have expanding bike lane networks',
      'Hydration is critical for summer riding. Consider bikes with frame bag mounts for water bottles',
    ],
    topCities: ['Austin', 'Houston', 'Dallas', 'San Antonio', 'Fort Worth'],
    metaDescription: 'Best electric bikes for Texas riders. E-bike laws in TX, top picks for flat terrain and hot weather, plus local dealers.',
    intro: 'Texas offers thousands of miles of flat, open roads that are ideal for e-bike riding. The growing bike infrastructure in Austin, Houston, and Dallas makes commuting practical, and the warm climate means you can ride most of the year.',
  },
  {
    slug: 'new-york',
    name: 'New York',
    abbreviation: 'NY',
    terrain: 'Urban density in NYC, rolling hills upstate. Bridge crossings and multi-modal commuting.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 14. Class 3 riders of any age must wear a helmet in NYC.',
    maxSpeed: '25 mph (Class 3, NYC limit)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on most bike paths. Class 3 allowed in NYC bike lanes but not on greenways or sidewalks.',
    lawSummary: 'New York legalized e-bikes statewide in 2020. NYC has additional local rules: Class 3 e-bikes are capped at 25 mph (not 28), and throttle-only operation is limited. All classes are allowed on streets and in bike lanes. E-bikes are banned from sidewalks statewide.',
    ridingTips: [
      'Folding e-bikes are popular in NYC for apartment storage and subway/bus transfers',
      'The Brooklyn Bridge and Manhattan Bridge have dedicated bike lanes',
      'Invest in a quality U-lock; bike theft is a real concern in the city',
      'Upstate NY has beautiful rail-trail networks for recreational riding',
    ],
    topCities: ['New York City', 'Brooklyn', 'Buffalo', 'Albany', 'Rochester'],
    metaDescription: 'Best electric bikes for New York. NYC e-bike laws, top picks for city commuting and upstate trails, plus where to buy.',
    intro: 'New York City\'s Citi Bike e-bike usage jumped 65% recently, and for good reason. E-bikes turn a sweaty, exhausting city commute into something you actually look forward to. Whether you are navigating Manhattan traffic or exploring Hudson Valley trails, the right e-bike makes all the difference.',
  },
  {
    slug: 'florida',
    name: 'Florida',
    abbreviation: 'FL',
    terrain: 'Almost entirely flat. Coastal breezes can create headwinds. Year-round warm weather.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on bike paths unless locally restricted. Class 3 on roads and bike lanes.',
    lawSummary: 'Florida adopted the three-class system in 2020. E-bikes are classified as bicycles. No license, registration, or insurance required. Riders must be at least 16 years old to operate a Class 3 e-bike.',
    ridingTips: [
      'Flat terrain and warm weather make Florida ideal for e-bikes with maximum range',
      'Salt air along the coast accelerates corrosion, so look for bikes with rust-resistant components',
      'Afternoon thunderstorms are common in summer. Fenders and water-resistant displays are worth it',
      'Many beach communities have dedicated cycling paths perfect for cruiser-style e-bikes',
    ],
    topCities: ['Miami', 'Tampa', 'Orlando', 'Jacksonville', 'Fort Lauderdale'],
    metaDescription: 'Best electric bikes for Florida. FL e-bike laws, top picks for flat coastal riding, and where to find dealers near you.',
    intro: 'Florida\'s flat terrain, warm climate, and growing network of bike paths make it one of the best states for e-bike riding. The lack of hills means you can prioritize range and comfort over raw motor power, and you will ride comfortably year-round.',
  },
  {
    slug: 'washington',
    name: 'Washington',
    abbreviation: 'WA',
    terrain: 'Hilly west side (Seattle), flat eastern plains. Frequent rain in western WA.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for all riders in many counties and cities (including King County/Seattle)',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 allowed on all bike paths. Class 2 and 3 allowed where local authorities permit.',
    lawSummary: 'Washington uses the three-class system. E-bikes are treated as bicycles. No state license or registration required. Many local jurisdictions (including Seattle and King County) require helmets for all ages.',
    ridingTips: [
      'Seattle hills require solid torque. Look for 60+ Nm mid-drive motors',
      'Rain is a constant from October through May. Hydraulic disc brakes and fenders are non-negotiable',
      'The Burke-Gilman Trail is one of the best urban bike paths in the country',
      'Eastern Washington is flat and dry, which is a completely different riding experience',
    ],
    topCities: ['Seattle', 'Tacoma', 'Bellevue', 'Spokane', 'Olympia'],
    metaDescription: 'Best electric bikes for Washington state. WA e-bike laws, picks for Seattle hills and rainy weather, plus local dealers.',
    intro: 'Seattle has emerged as one of America\'s top e-bike cities, and the rest of Washington is catching up fast. The city\'s hills, reliable bike infrastructure, and rain-or-shine cycling culture make a capable e-bike the smartest transportation investment you can make.',
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    abbreviation: 'OR',
    terrain: 'Hilly and wet in Portland metro, mountainous east side. Strong cycling culture.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement (local rules may vary)',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '1000W',
    bikePaths: 'Class 1 and 2 allowed on bike paths. Class 3 on roads and bike lanes only.',
    lawSummary: 'Oregon allows e-bikes up to 1000W, which is higher than most states. The three-class system applies. No license or registration required. Portland has one of the most extensive bike lane networks in the US.',
    ridingTips: [
      'Portland is consistently ranked the most bike-friendly city in the US',
      'Oregon allows up to 1000W motors, giving you more options than most states',
      'The rain never really stops from fall through spring, so water resistance matters',
      'The Historic Columbia River Highway offers spectacular e-bike touring',
    ],
    topCities: ['Portland', 'Eugene', 'Salem', 'Bend', 'Corvallis'],
    metaDescription: 'Best electric bikes for Oregon. OR e-bike laws (up to 1000W allowed), top picks for Portland riding, and local dealers.',
    intro: 'Portland is the cycling capital of America, and Oregon\'s e-bike laws are among the most rider-friendly. The state allows motors up to 1000W (higher than the 750W limit in most states), and the infrastructure supports year-round commuting despite the rain.',
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    abbreviation: 'CO',
    terrain: 'High altitude, steep mountain terrain, and flat plains east of the Rockies.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement for adults',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on most multi-use paths. Class 3 restricted to roads. Some mountain trails open to Class 1 only.',
    lawSummary: 'Colorado uses the three-class system and was one of the early adopters. Local jurisdictions can open natural-surface trails to Class 1 e-bikes. No license or registration required. Boulder and Denver have strong cycling infrastructure.',
    ridingTips: [
      'Altitude matters: batteries drain faster at elevation, so plan for 10-20% less range above 5,000 ft',
      'Mountain terrain demands a mid-drive motor for efficient climbing',
      'Boulder has more bikes than cars on some routes, and the infrastructure reflects it',
      'Cold winters reduce battery capacity. Store your battery indoors when not riding',
    ],
    topCities: ['Denver', 'Boulder', 'Colorado Springs', 'Fort Collins', 'Aspen'],
    metaDescription: 'Best electric bikes for Colorado. CO e-bike laws, top picks for mountain terrain and high altitude, plus local dealers.',
    intro: 'Colorado\'s combination of mountain terrain, outdoor culture, and progressive cycling infrastructure makes it a natural fit for e-bikes. A strong motor is essential for the Rockies, and you will want to factor altitude into your battery range expectations.',
  },
  {
    slug: 'hawaii',
    name: 'Hawaii',
    abbreviation: 'HI',
    terrain: 'Volcanic hills, coastal roads, tropical climate. Short distances between towns.',
    classSystem: false,
    licenseRequired: true,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '20 mph',
    maxWattage: '750W',
    bikePaths: 'E-bikes allowed where bicycles are allowed, subject to local rules.',
    lawSummary: 'Hawaii has the highest e-bike search interest per capita in the US but has not adopted the three-class system. A valid driver\'s license is required. E-bikes are limited to 20 mph. Check individual island regulations, as county rules can vary.',
    ridingTips: [
      'Salt air and humidity accelerate corrosion, so stainless hardware and sealed electronics matter',
      'Short distances between towns mean you do not need a massive battery',
      'Trade winds can create strong headwinds on coastal roads',
      'Many tourist areas have e-bike rental shops if you want to try before buying',
    ],
    topCities: ['Honolulu', 'Maui', 'Kailua', 'Hilo', 'Kona'],
    metaDescription: 'Best electric bikes for Hawaii. HI e-bike regulations, top picks for island riding, and what to know before buying.',
    intro: 'Hawaii leads the nation in e-bike search interest per capita. The islands\' short distances, year-round warm weather, and scenic coastal roads make e-bikes a practical alternative to driving. Keep in mind that Hawaii has not adopted the standard three-class system, so the rules are a bit different here.',
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    abbreviation: 'AZ',
    terrain: 'Desert flat with some mountain terrain. Extreme summer heat.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on bike paths. Class 3 on roads and bike lanes.',
    lawSummary: 'Arizona adopted the three-class system. E-bikes are classified as bicycles. No license, registration, or insurance required. Riders under 18 on Class 3 bikes should check local helmet rules.',
    ridingTips: [
      'Summer temperatures regularly exceed 110F. Ride early morning or after sunset',
      'Flat desert terrain is ideal for long-range riding on lower assist levels',
      'Scottsdale and Tempe have excellent cycling infrastructure',
      'UV exposure degrades rubber and plastic over time. Store your e-bike out of direct sun',
    ],
    topCities: ['Phoenix', 'Scottsdale', 'Tucson', 'Tempe', 'Mesa'],
    metaDescription: 'Best electric bikes for Arizona. AZ e-bike laws, top picks for desert riding and extreme heat, plus local dealers.',
    intro: 'Arizona\'s flat desert terrain and 300+ days of sunshine make it ideal for e-bike riding, as long as you respect the summer heat. The state\'s cities are investing heavily in cycling infrastructure, and the lack of hills means your battery goes further.',
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    abbreviation: 'IL',
    terrain: 'Flat to gently rolling. Cold winters, warm summers. Chicago is a major cycling city.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement (recommended)',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on multi-use paths. Class 3 on roads.',
    lawSummary: 'Illinois uses the three-class system. No license or registration required. Chicago has one of the largest bike-share systems in the country (Divvy), and nearly half of Divvy rides are now on e-bikes.',
    ridingTips: [
      'Chicago cycling is up 119% over four years, driven largely by e-bikes',
      'The Lakefront Trail is 18 miles of car-free riding along Lake Michigan',
      'Winter riding is viable with the right gear but expect 15-25% less battery range in cold weather',
      'Flat terrain means virtually any e-bike will handle the geography well',
    ],
    topCities: ['Chicago', 'Evanston', 'Naperville', 'Springfield', 'Champaign'],
    metaDescription: 'Best electric bikes for Illinois. IL e-bike laws, top picks for Chicago commuting, and where to buy near you.',
    intro: 'Chicago has become one of America\'s biggest e-bike success stories, with cycling numbers up over 100% in recent years. Nearly half of all bike-share rides in the city are now on e-bikes. The flat terrain and expanding bike lane network make the whole state accessible on two wheels.',
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    abbreviation: 'NC',
    terrain: 'Mountains in the west, piedmont rolling hills, flat coastal plain east.',
    classSystem: false,
    licenseRequired: false,
    helmetRequired: 'No statewide requirement, though riders under 16 are advised to wear one.',
    maxSpeed: '20 mph (motor-powered)',
    maxWattage: '750W',
    bikePaths: 'E-bikes are allowed wherever bicycles are allowed, since state law defines them as bicycles rather than motor vehicles.',
    lawSummary: 'North Carolina has not adopted the three-class e-bike system most states use. State law instead defines a single "electric assisted bicycle" category: working pedals, 750 watts or less, and a motor-only top speed of 20 mph. There is no license or registration requirement. A bill to adopt the three-class system (which would add a 28 mph Class 3 tier) has been introduced but has not passed as of 2026, so a faster pedal-assist-only e-bike does not have a clear legal category here yet. The Blue Ridge Parkway has its own specific rules for e-bikes on certain sections.',
    ridingTips: [
      'North Carolina does not have a Class 3 category yet, so check that a higher-speed pedal-assist e-bike is street-legal here before buying',
      'Western NC mountains are serious climbing territory. A mid-drive motor is highly recommended',
      'The Triangle area (Raleigh-Durham-Chapel Hill) has strong cycling infrastructure',
      'Humidity and summer heat make throttle-assist popular for taking breaks from pedaling',
      'The Outer Banks has scenic but windy coastal riding',
    ],
    topCities: ['Charlotte', 'Raleigh', 'Asheville', 'Durham', 'Wilmington'],
    metaDescription: 'Best electric bikes for North Carolina. NC e-bike laws (no three-class system), picks for mountain and coastal terrain, plus local dealers.',
    intro: 'North Carolina offers some of the most diverse riding terrain in the US, from the Blue Ridge Mountains to the Outer Banks coastline. The growing cycling infrastructure in Charlotte and the Triangle makes commuting viable, and the mountains offer world-class recreational riding, but unlike most states, North Carolina has not yet adopted the standard three-class e-bike law.',
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    abbreviation: 'VA',
    terrain: 'Rolling hills, Appalachian mountains in the west, flat tidewater region east.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 14',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 on all bike paths. Class 2 and 3 where locally permitted.',
    lawSummary: 'Virginia uses the three-class system. E-bikes are classified as bicycles. No license or registration required. Northern Virginia benefits from DC-area bike infrastructure. Virginia Beach and Richmond have growing cycling networks.',
    ridingTips: [
      'Northern Virginia connects to the extensive DC bike path network',
      'The Virginia Creeper Trail is one of the most popular rail-trails in the country',
      'Four distinct seasons mean you will deal with heat, cold, and rain throughout the year',
      'Richmond has become an underrated cycling city with improving infrastructure',
    ],
    topCities: ['Arlington', 'Richmond', 'Virginia Beach', 'Alexandria', 'Norfolk'],
    metaDescription: 'Best electric bikes for Virginia. VA e-bike laws, top picks for DC-area commuting and trail riding, plus dealers.',
    intro: 'Virginia\'s location between the Appalachian Mountains and the Atlantic coast gives riders diverse terrain, and the northern part of the state connects directly to DC\'s excellent cycling infrastructure. Whether you commute into the capital or explore the Virginia Creeper Trail, the right e-bike opens up the state.',
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    abbreviation: 'GA',
    terrain: 'Rolling hills in Atlanta, flat coastal plain toward Savannah. Hot, humid summers.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '20 mph (Class 1 and 2), 28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 allowed on multi-use paths. Class 2 and 3 on roads and bike lanes.',
    lawSummary: 'Georgia adopted the three-class system. E-bikes are classified as bicycles. No license or registration required. Atlanta has been expanding its BeltLine trail network, which is a major cycling corridor.',
    ridingTips: [
      'Atlanta\'s BeltLine is a 22-mile loop of trails connecting 45 neighborhoods',
      'Summer humidity is intense. A throttle lets you take pedaling breaks without stopping',
      'The rolling hills around Atlanta benefit from a motor with decent torque',
      'Savannah\'s flat, compact layout is perfect for casual e-bike cruising',
    ],
    topCities: ['Atlanta', 'Savannah', 'Athens', 'Augusta', 'Decatur'],
    metaDescription: 'Best electric bikes for Georgia. GA e-bike laws, top picks for Atlanta commuting and Savannah cruising, plus dealers.',
    intro: 'Atlanta\'s expanding BeltLine trail network is turning the city into a cycling destination, and e-bikes make the rolling hills manageable for daily commuting. The combination of warm weather, growing infrastructure, and a car-heavy city desperate for alternatives makes Georgia a strong e-bike market.',
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    abbreviation: 'MA',
    terrain: 'Hilly in the west, rolling terrain around Boston. Cold winters.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16. Recommended for all ages.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 on all paths. Class 2 where locally permitted. Class 3 on roads.',
    lawSummary: 'Massachusetts updated its e-bike laws in recent years to adopt the three-class system. E-bikes are treated as bicycles. No license or registration required. Boston has an expanding protected bike lane network.',
    ridingTips: [
      'Boston has notoriously narrow streets, so a compact or folding e-bike is practical',
      'The Minuteman Bikeway and Cape Cod Rail Trail are excellent recreational rides',
      'Winter riding is feasible but battery range drops significantly below freezing',
      'Cambridge and Somerville have some of the best cycling infrastructure in the state',
    ],
    topCities: ['Boston', 'Cambridge', 'Somerville', 'Worcester', 'Salem'],
    metaDescription: 'Best electric bikes for Massachusetts. MA e-bike laws, picks for Boston commuting and Cape Cod trails, plus dealers.',
    intro: 'Boston\'s dense urban core and limited parking make e-bikes a genuinely practical commuting option. The combination of expanding protected bike lanes, excellent rail-trail networks, and a compact metro area means many Bostonians can replace car trips entirely with an e-bike.',
  },
  {
    slug: 'utah',
    name: 'Utah',
    abbreviation: 'UT',
    terrain: 'Mountain terrain, high desert, dramatic elevation changes. Four distinct seasons.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 on bike paths and some natural-surface trails. Class 2 and 3 on roads.',
    lawSummary: 'Utah uses the three-class system. E-bikes are treated as bicycles. No license or registration required. Some national parks and BLM land in Utah allow Class 1 e-bikes on trails where traditional bikes are permitted.',
    ridingTips: [
      'Utah has the third-highest e-bike interest in the US per capita',
      'High altitude (4,000-6,000 ft in the valleys) reduces battery range by 10-15%',
      'Salt Lake City\'s grid layout and flat valley floor make it great for commuting',
      'Moab and Park City offer world-class trail riding on Class 1 e-bikes',
    ],
    topCities: ['Salt Lake City', 'Provo', 'Park City', 'Moab', 'Ogden'],
    metaDescription: 'Best electric bikes for Utah. UT e-bike laws, top picks for mountain terrain and trail riding, plus where to buy.',
    intro: 'Utah ranks third in the nation for e-bike interest per capita, and it is easy to see why. The state offers everything from flat Salt Lake City commuting to epic Moab trail riding. Altitude is a factor here, so plan for reduced battery range in the mountain valleys.',
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    abbreviation: 'MI',
    terrain: 'Generally flat to gently rolling. Cold winters, pleasant summers. Extensive lakefront.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on bike paths. Class 3 on roads.',
    lawSummary: 'Michigan uses the three-class system. E-bikes are treated as bicycles. No license or registration required. The state has been investing in cycling infrastructure, particularly in the Detroit metro and Grand Rapids areas.',
    ridingTips: [
      'Michigan has over 2,600 miles of rail trails, more than almost any other state',
      'Lakefront riding is beautiful but windy. A headwind eats battery fast',
      'Winter riding is possible but limited. Store your battery indoors between rides',
      'Mackinac Island bans motorized vehicles but allows Class 1 e-bikes on some paths',
    ],
    topCities: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Traverse City', 'Lansing'],
    metaDescription: 'Best electric bikes for Michigan. MI e-bike laws, top picks for rail-trail riding and lakefront commuting, plus dealers.',
    intro: 'Michigan has over 2,600 miles of rail trails and a growing cycling culture in cities like Grand Rapids and Ann Arbor. The flat terrain is forgiving for any motor type, and the extensive trail network makes recreational riding a year-round attraction (at least from April through November).',
  },
  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    abbreviation: 'PA',
    terrain: 'Hilly, especially in Pittsburgh. Philadelphia is relatively flat. Rural mountain areas.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 12',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on bike paths. Class 3 on roads. Some rail-trails allow e-bikes.',
    lawSummary: 'Pennsylvania adopted the three-class e-bike system. E-bikes are classified as pedalcycles. No license or registration required. The state has an extensive network of rail-trails, with some allowing e-bikes.',
    ridingTips: [
      'Pittsburgh\'s hills are no joke. If you commute there, get a mid-drive with at least 60 Nm',
      'Philadelphia is relatively flat and has a growing protected bike lane network',
      'The Great Allegheny Passage (150 miles) is one of the best long-distance bike trails in the US',
      'Pennsylvania has four seasons. Expect cold winters and hot, humid summers',
    ],
    topCities: ['Philadelphia', 'Pittsburgh', 'State College', 'Harrisburg', 'Lancaster'],
    metaDescription: 'Best electric bikes for Pennsylvania. PA e-bike laws, picks for Philadelphia commuting and Pittsburgh hills, plus dealers.',
    intro: 'Pennsylvania offers two very different riding experiences: flat Philadelphia with its expanding bike lane network, and hilly Pittsburgh where a powerful motor turns impossible commutes into pleasant rides. The state also has incredible rail-trail riding, including the 150-mile Great Allegheny Passage.',
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    abbreviation: 'NJ',
    terrain: 'Mostly flat with some rolling hills. Dense urban areas, beach communities.',
    classSystem: false,
    licenseRequired: true,
    helmetRequired: 'Required for riders under 17',
    maxSpeed: '20 mph',
    maxWattage: '750W',
    bikePaths: 'E-bikes allowed where bicycles are allowed, subject to local rules.',
    lawSummary: 'In 2026, New Jersey eliminated the three-class system and reclassified all e-bikes as "motorized bicycles." A valid driver\'s license is required. E-bikes are limited to 20 mph motor-assisted speed. Rules may differ from neighboring states, so check current regulations.',
    ridingTips: [
      'New Jersey\'s 2026 law change means your rules differ from neighboring NY and PA, so pay attention at state borders',
      'The Jersey Shore has excellent boardwalk and coastal riding',
      'Dense urban areas in northern NJ benefit from folding e-bikes for train commuters',
      'The D&R Canal towpath offers 70+ miles of flat, scenic riding',
    ],
    topCities: ['Jersey City', 'Newark', 'Hoboken', 'Princeton', 'Asbury Park'],
    metaDescription: 'Best electric bikes for New Jersey. NJ e-bike regulations (updated 2026), top picks for Shore riding and commuting.',
    intro: 'New Jersey made a significant regulatory change in 2026 by eliminating the three-class system and reclassifying e-bikes as "motorized bicycles." This means you need a valid driver\'s license to ride one. Despite the stricter rules, e-bikes remain popular for Shore riding, urban commuting, and canal trail exploring.',
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    abbreviation: 'MN',
    terrain: 'Flat to gently rolling. Harsh winters, pleasant summers. Lake country.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '1000W',
    bikePaths: 'Class 1 and 2 on state trails. Class 3 on roads. Some trails allow all classes.',
    lawSummary: 'Minnesota allows e-bikes up to 1000W, one of the highest limits in the nation. The three-class system applies. No license or registration required. Minneapolis has been ranked among the top bike-friendly cities in the US.',
    ridingTips: [
      'Minnesota allows 1000W motors, giving you more power options than most states',
      'Minneapolis has over 200 miles of on- and off-street bikeways',
      'Winter riding is a real thing here. Fat-tire e-bikes are popular for snow riding',
      'The Midtown Greenway is a car-free commuting corridor through Minneapolis',
    ],
    topCities: ['Minneapolis', 'St. Paul', 'Duluth', 'Rochester', 'Bloomington'],
    metaDescription: 'Best electric bikes for Minnesota. MN e-bike laws (up to 1000W allowed), top picks for Minneapolis commuting and winter riding.',
    intro: 'Minneapolis consistently ranks among America\'s most bike-friendly cities, with over 200 miles of bikeways and a culture that rides year-round. Minnesota also allows motors up to 1000W (higher than most states), giving you extra power for headwinds and winter conditions.',
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    abbreviation: 'OH',
    terrain: 'Flat in the northwest, rolling hills in the southeast. Four-season climate.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '20 mph (motor-assisted)',
    maxWattage: '750W',
    bikePaths: 'E-bikes allowed on most multi-use paths. Local jurisdictions may restrict.',
    lawSummary: 'Ohio classifies e-bikes as bicycles with a 20 mph motor-assisted speed limit and 750W maximum. No license or registration required. The state has extensive rail-trail networks and growing urban cycling infrastructure.',
    ridingTips: [
      'Ohio has over 1,800 miles of multi-use trails, perfect for e-bike exploring',
      'Columbus has invested heavily in cycling infrastructure in recent years',
      'The Ohio to Erie Trail runs 326 miles from Cleveland to Cincinnati',
      'Budget-friendly e-bikes perform well on Ohio\'s mostly flat terrain',
    ],
    topCities: ['Columbus', 'Cleveland', 'Cincinnati', 'Dayton', 'Toledo'],
    metaDescription: 'Best electric bikes for Ohio. OH e-bike laws, top picks for trail riding and city commuting, plus local dealers.',
    intro: 'Ohio\'s flat terrain and extensive trail network (over 1,800 miles of multi-use trails) make it an underrated e-bike state. The Ohio to Erie Trail alone stretches 326 miles from Cleveland to Cincinnati. Cities like Columbus are investing in cycling infrastructure, making daily commuting increasingly practical.',
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    abbreviation: 'TN',
    terrain: 'Rolling hills around Nashville, Smoky Mountain foothills east, flat delta near Memphis.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on multi-use paths and greenways. Class 3 on roads and bike lanes.',
    lawSummary: 'Tennessee adopted the three-class e-bike system, classifying e-bikes as bicycles rather than motor vehicles. No license, registration, or insurance is required. Riders under 16 must wear a helmet. Cities set their own rules for local greenways.',
    ridingTips: [
      'Nashville\'s hills and humidity make a mid-drive motor with solid torque worth the extra cost',
      'The Smoky Mountains foothills in East Tennessee demand a strong climbing motor',
      'Memphis and the western delta are flat, so range matters more than torque there',
      'Summer humidity is intense; look for a bike with good ventilation around the battery and controller',
    ],
    topCities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Franklin'],
    metaDescription: 'Best electric bikes for Tennessee. TN e-bike laws, top picks for Nashville hills and Memphis flats, plus local dealers.',
    intro: 'Tennessee spans everything from the flat Mississippi Delta near Memphis to the steep foothills of the Smoky Mountains, so the right e-bike really depends on where in the state you ride. Nashville\'s growing greenway network and warm climate make e-bikes an increasingly common sight on the daily commute.',
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    abbreviation: 'MO',
    terrain: 'Mostly flat to gently rolling, Ozark hills in the south. Humid summers, cold winters.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on multi-use trails. Class 3 on roads and bike lanes.',
    lawSummary: 'Missouri adopted the three-class e-bike system, treating e-bikes as bicycles rather than motorized vehicles. No license, registration, or insurance is required for any class. Local trail managers can set their own e-bike access rules on multi-use paths.',
    ridingTips: [
      'The Katy Trail, at 240+ miles, is the longest rail-trail in the US and a major reason to own an e-bike here',
      'St. Louis and Kansas City are both largely flat, so a budget hub-motor bike handles daily commuting fine',
      'The Ozark hills in southern Missouri call for more torque if that is where you ride',
      'Humid summers and cold winters mean sealed electronics and a weatherproof display are worth paying for',
    ],
    topCities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'],
    metaDescription: 'Best electric bikes for Missouri. MO e-bike laws, top picks for the Katy Trail and city commuting, plus local dealers.',
    intro: 'Missouri is home to the Katy Trail, the longest continuous rail-trail in the country, plus two flat, bike-friendly metro areas in St. Louis and Kansas City. Most of the state rewards range and comfort over raw climbing power, except for the Ozark hills in the south.',
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    abbreviation: 'MD',
    terrain: 'Flat coastal plain east, rolling Piedmont around Baltimore, mountains in the west.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 allowed on all bike paths. Class 2 and 3 where locally permitted; Class 3 generally restricted from natural-surface trails.',
    lawSummary: 'Maryland adopted the three-class e-bike system and classifies e-bikes as bicycles. No license, registration, or insurance is required. Riders under 16 must wear a helmet. Maryland\'s DC suburbs benefit from the region\'s extensive shared bike infrastructure with Virginia and DC.',
    ridingTips: [
      'DC-area suburbs like Bethesda and Silver Spring connect directly to the Capital Crescent Trail',
      'Baltimore\'s rolling hills benefit from a motor with at least 60 Nm of torque',
      'The Eastern Shore is flat and rural, ideal for long-range touring rides',
      'Western Maryland\'s mountain terrain around Cumberland is genuinely challenging; consider a mid-drive there',
    ],
    topCities: ['Baltimore', 'Annapolis', 'Bethesda', 'Silver Spring', 'Frederick'],
    metaDescription: 'Best electric bikes for Maryland. MD e-bike laws, top picks for DC-suburb commuting and Baltimore hills, plus dealers.',
    intro: 'Maryland\'s DC suburbs plug directly into the capital region\'s excellent trail network, while Baltimore\'s rolling hills and the flat Eastern Shore offer very different riding experiences within the same state. Whichever part of Maryland you call home, the right e-bike makes the daily commute or weekend trail ride easier.',
  },
  {
    slug: 'wisconsin',
    name: 'Wisconsin',
    abbreviation: 'WI',
    terrain: 'Flat to gently rolling in the south, hillier Driftless Area in the southwest. Cold, snowy winters.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on multi-use trails. Class 3 on roads and bike lanes; some trail systems restrict Class 3.',
    lawSummary: 'Wisconsin adopted the three-class e-bike system, treating e-bikes as bicycles. No license, registration, or insurance is required for any class. Madison and Milwaukee both have active cycling advocacy and expanding bike lane networks.',
    ridingTips: [
      'Madison consistently ranks among the most bike-friendly mid-sized cities in the US',
      'The Driftless Area in southwestern Wisconsin has genuinely hilly, scenic riding that rewards more torque',
      'Winter riding drops off sharply here; plan on storing your battery indoors from December through February',
      'Wisconsin has hundreds of miles of former rail-bed trails, including the Elroy-Sparta State Trail',
    ],
    topCities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Eau Claire'],
    metaDescription: 'Best electric bikes for Wisconsin. WI e-bike laws, top picks for Madison commuting and rail-trail riding, plus dealers.',
    intro: 'Madison\'s reputation as one of America\'s best cycling cities, combined with hundreds of miles of converted rail-trails statewide, makes Wisconsin a strong e-bike market outside the harshest winter months. The Driftless Area\'s hills are a nice change of pace from the flat terrain most of the state offers.',
  },
  {
    slug: 'nevada',
    name: 'Nevada',
    abbreviation: 'NV',
    terrain: 'Desert flat around Las Vegas, high-desert and mountains around Reno. Extreme summer heat.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 18',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on shared-use paths. Class 3 on roads and bike lanes.',
    lawSummary: 'Nevada adopted the three-class e-bike system and treats e-bikes as bicycles rather than motor vehicles. No license, registration, or insurance is required. Riders under 18 must wear a helmet.',
    ridingTips: [
      'Las Vegas summer heat regularly exceeds 105F; ride early morning or after sunset from June through September',
      'Reno sits at higher elevation with real hills, so budget for reduced range and consider more torque',
      'Flat desert terrain around Las Vegas is ideal for long-range cruising on lower assist levels',
      'Dust and grit are hard on drivetrains here; a fully enclosed chain guard or belt drive is worth seeking out',
    ],
    topCities: ['Las Vegas', 'Reno', 'Henderson', 'Sparks', 'Carson City'],
    metaDescription: 'Best electric bikes for Nevada. NV e-bike laws, top picks for Las Vegas heat and Reno hills, plus local dealers.',
    intro: 'Nevada is a state of contrasts: the flat desert sprawl of Las Vegas versus Reno\'s higher elevation and real hills. Both share brutal summer heat and dry, dusty conditions that put extra demands on a bike\'s components, but the terrain difference means the right e-bike varies a lot depending on which end of the state you\'re in.',
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    abbreviation: 'IN',
    terrain: 'Mostly flat to gently rolling. Hillier terrain in the south around Brown County and the Hoosier National Forest.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for Class 3 riders and passengers under 18. No statewide requirement for Class 1/2 adults.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 generally allowed on multi-use paths and trails. Class 3 restricted to roads and bike lanes unless local ordinance says otherwise.',
    lawSummary: 'Indiana recognizes the three-class e-bike system and treats compliant e-bikes as bicycles, not motor vehicles. No license, registration, or insurance is required. Operators must be at least 15, and anyone under 18 riding or riding as a passenger on a Class 3 e-bike must wear a helmet. Local park systems and trail authorities can set their own additional rules.',
    ridingTips: [
      'Indianapolis and the northern half of the state are flat and well-suited to lower-torque, long-range commuter builds',
      'Brown County and the Hoosier National Forest in the south have real hills, so budget for a mid-drive or higher-torque hub motor if you ride there',
      'Winters bring salt and slush on roads; sealed drivetrains and disc brakes hold up better than rim brakes',
      'The Monon Trail and other rail-trail conversions offer long, flat stretches ideal for Class 1 and 2 e-bikes',
    ],
    topCities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'Bloomington', 'Carmel'],
    metaDescription: 'Best electric bikes for Indiana. IN e-bike laws, top picks for flat terrain and southern hills, plus local dealers.',
    intro: 'Indiana\'s flat-to-rolling terrain and growing trail network, including the Monon Trail through Indianapolis, make it an easy state to commute and cruise on an e-bike. Head south toward Brown County and the hills pick up, so the right motor depends on which part of the state you\'re riding in.',
  },
  {
    slug: 'connecticut',
    name: 'Connecticut',
    abbreviation: 'CT',
    terrain: 'Rolling hills across most of the state, steeper terrain in the northwest Litchfield Hills, flatter along the shoreline.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for every rider and passenger, regardless of age, on any class of e-bike. One of the strictest helmet rules in the US.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 3 e-bikes are not allowed on bicycle paths, multi-use trails, or natural-surface trails statewide. Class 1 and 2 access varies by local ordinance.',
    lawSummary: 'Connecticut adopted the three-class e-bike system but layered on stricter rules than most states: every rider and passenger must wear a helmet regardless of age or class, Class 3 riders must be at least 16, and Class 3 e-bikes are barred from bike paths and multi-use trails statewide. No license, registration, or insurance is required.',
    ridingTips: [
      'Helmets are legally required here for every rider, unlike most states, so factor that into your buying checklist',
      'The Litchfield Hills in the northwest corner call for more torque than the flatter shoreline towns',
      'If you plan to ride trails and paths, a Class 1 or 2 e-bike keeps more options open since Class 3 is barred from many of them',
      'Coastal humidity and road salt in winter make sealed connectors and corrosion-resistant hardware worth paying for',
    ],
    topCities: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport', 'Norwalk'],
    metaDescription: 'Best electric bikes for Connecticut. CT e-bike laws (all-age helmet rule), top picks for hilly terrain, plus local dealers.',
    intro: 'Connecticut combines rolling New England hills with a dense, walkable shoreline, and it has one of the strictest e-bike helmet laws in the country: every rider, at every age, must wear one. Keep that rule and the Class 3 trail restriction in mind before deciding which class of bike fits how you actually plan to ride.',
  },
  {
    slug: 'alabama',
    name: 'Alabama',
    abbreviation: 'AL',
    terrain: 'Flat and humid along the Gulf Coast near Mobile, rolling Piedmont hills through Birmingham and Montgomery, Appalachian foothills in the north near Huntsville.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for all riders under 16 on any class, and for all Class 3 riders and passengers regardless of age.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Sidewalk riding is prohibited statewide, and cyclists must use a designated sidepath where one exists alongside the road.',
    lawSummary: 'Alabama recognizes Class 1, 2, and 3 e-bikes and treats them as bicycles. No license, registration, or insurance is required. Class 3 operators must be at least 16. Riders under 16 must wear a helmet on any class, and Class 3 riders and passengers must wear one regardless of age. Two rules trip up newcomers: sidewalk riding is banned statewide, and you must use a marked sidepath if the road has one.',
    ridingTips: [
      'Sidewalk riding is against state law here, unlike many states, so plan routes on roads or designated paths',
      'Gulf Coast humidity near Mobile is hard on drivetrains; look for sealed bearings and corrosion-resistant chains',
      'Birmingham and Montgomery have real rolling hills, so budget more torque than you would for a coastal commuter build',
      'Huntsville sits at the edge of the Appalachian foothills; a mid-drive motor pays off on the steeper northern routes',
    ],
    topCities: ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa'],
    metaDescription: 'Best electric bikes for Alabama. AL e-bike laws (no sidewalk riding), top picks for Gulf Coast and Piedmont terrain, plus local dealers.',
    intro: 'Alabama spans humid Gulf Coast flats, rolling Piedmont hills through its biggest cities, and Appalachian foothills in the north, so the right e-bike depends heavily on where in the state you ride. Two state rules are easy to miss: sidewalk riding is banned outright, and you\'re required to use a sidepath where one is marked.',
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    abbreviation: 'SC',
    terrain: 'Flat coastal Lowcountry around Charleston and Myrtle Beach, rolling Midlands around Columbia, foothills and mountains in the Upstate near Greenville.',
    classSystem: false,
    licenseRequired: false,
    helmetRequired: 'No statewide helmet requirement for any age, though riders under 16 are advised to wear one.',
    maxSpeed: '20 mph (motor-powered)',
    maxWattage: '750W',
    bikePaths: 'E-bikes are allowed wherever bicycles are allowed, since state law defines them as bicycles rather than motor vehicles.',
    lawSummary: 'South Carolina has not adopted the three-class e-bike system most states use. State law instead defines a single category of "electric-assist bicycle": 750 watts or less, with motor-only speed under 20 mph. There is no license, registration, or insurance requirement, and no statewide helmet law for riders of any age. Because there is no Class 3 designation, a 28 mph pedal-assist e-bike does not fit neatly into the state\'s legal definition, so check local rules before buying one of those for South Carolina roads.',
    ridingTips: [
      'South Carolina does not use the Class 1/2/3 system other states do, so double-check that a higher-speed e-bike is street-legal here before buying',
      'The flat Lowcountry around Charleston and Myrtle Beach is ideal for lower-torque, long-range coastal cruising',
      'Salt air along the coast accelerates corrosion; sealed electronics and stainless hardware are worth the upgrade',
      'The Upstate near Greenville has real foothill climbs, so budget more torque if that is where you will be riding',
    ],
    topCities: ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach', 'Mount Pleasant'],
    metaDescription: 'Best electric bikes for South Carolina. SC e-bike laws (no three-class system), top picks for coastal and Upstate terrain, plus local dealers.',
    intro: 'South Carolina stretches from the flat, salt-air Lowcountry around Charleston to the foothill climbs of the Upstate near Greenville, and its e-bike law looks different from most states: there is no Class 1/2/3 system, just a single 750-watt, 20-mph definition. Know that distinction before you buy, especially if you are considering a higher-speed pedal-assist bike.',
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    abbreviation: 'KY',
    terrain: 'Rolling Bluegrass hills around Lexington, flatter Ohio River valley near Louisville and western Kentucky, steep Appalachian terrain in the east near Pikeville.',
    classSystem: false,
    licenseRequired: false,
    helmetRequired: 'No statewide requirement. Some local park systems, including Louisville Metro Parks, require helmets for riders under 18.',
    maxSpeed: 'Not defined by class; treated as a bicycle',
    maxWattage: '750W (typical; not codified in a dedicated e-bike statute)',
    bikePaths: 'E-bikes are handled as bicycles under state bicycle-safety rules. Check local trail and park authorities, since rules vary by jurisdiction.',
    lawSummary: 'Kentucky is one of the few states that has not enacted a three-class e-bike law. There is no statewide statute defining Class 1, 2, or 3, and no state helmet, age, license, registration, or insurance requirement for e-bikes. In practice, e-bikes are treated as bicycles under the state\'s general bicycle-safety regulation. Local rules matter more here than in most states; for example, Louisville Metro Parks requires riders under 18 to wear a helmet even though the state does not.',
    ridingTips: [
      'Kentucky has no statewide e-bike classification, so rules can vary more by city or park system than in most states; check local ordinances before you ride',
      'The Bluegrass region around Lexington has steady rolling hills that reward a higher-torque motor over a pure long-range build',
      'Louisville and the Ohio River valley are comparatively flat and well suited to commuting',
      'Eastern Kentucky\'s Appalachian terrain near Pikeville is genuinely mountainous; a mid-drive motor with strong climbing torque is worth the investment there',
    ],
    topCities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
    metaDescription: 'Best electric bikes for Kentucky. KY e-bike laws (no statewide class system), top picks for Bluegrass hills and Appalachian terrain, plus local dealers.',
    intro: 'Kentucky ranges from the rolling Bluegrass hills around Lexington to the flatter Ohio River valley near Louisville to genuinely mountainous terrain in the Appalachian east, and unlike most states, it has no statewide e-bike classification law at all. Local rules fill the gap, so it\'s worth checking your city or park system\'s own policy alongside picking a bike suited to the terrain.',
  },
  {
    slug: 'louisiana',
    name: 'Louisiana',
    abbreviation: 'LA',
    terrain: 'Flat, humid Gulf coastal plains and bayou wetlands around New Orleans, flatter still in the Mississippi Delta, gentle rolling hills up near Shreveport.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for all Class 3 riders and passengers regardless of age; no one under 12 may operate a Class 3 e-bike. No helmet requirement for Class 1 or Class 2.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Local agencies can restrict or ban e-bikes on shared-use paths; sidewalk access is set by local ordinance.',
    lawSummary: 'Louisiana uses the standard three-class e-bike system and treats compliant e-bikes as bicycles, not motor vehicles, for most traffic rules. No license, registration, or insurance is required for any class. Class 3 e-bikes carry stricter rules than most states: a helmet is mandatory for every rider and passenger regardless of age, and no one under 12 may operate one. A first violation of the helmet rule is a $50 fine that can be waived by showing proof of purchasing a compliant helmet.',
    ridingTips: [
      'Gulf humidity and salt air near New Orleans mean sealed electronics and corrosion-resistant hardware are worth paying for',
      'Flat Delta and coastal terrain favors range and comfort over climbing torque',
      'Class 3 riders of any age need a helmet here, stricter than most states, so factor that into your buying decision if you want the higher speed cap',
      'Afternoon heat and sudden storms are common; fenders and a stable low-speed handling feel matter more than top-end speed',
    ],
    topCities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
    metaDescription: 'Best electric bikes for Louisiana. LA e-bike laws (all-age Class 3 helmet rule), top picks for Gulf coast and Delta terrain, plus local dealers.',
    intro: 'Louisiana runs flat and humid from the bayou wetlands around New Orleans to the Mississippi Delta, with only gentle rolling terrain up near Shreveport. Its e-bike law follows the standard three-class system but adds a stricter twist: Class 3 helmet use is required for every rider, not just minors, so it is worth knowing before you pick a higher-speed bike.',
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    abbreviation: 'OK',
    terrain: 'Flat to gently rolling Great Plains across most of the state, Ozark foothills in the northeast, the Wichita Mountains rising in the southwest.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No statewide helmet requirement for any age or class. Norman requires helmets for riders under 18 within city limits.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'All three classes are allowed on bike and multi-use paths by default; unpaved, non-motorized natural-surface trails are off-limits unless a trail authority specifically permits e-bikes.',
    lawSummary: 'Oklahoma adopted the three-class e-bike system in 2019 and treats compliant e-bikes as bicycles. No license, registration, or insurance is required for any class. Class 3 riders must be at least 16 and the bike must have a working speedometer. Unlike most three-class states, Oklahoma has no statewide helmet law at all; the only local exception found is Norman\'s under-18 rule.',
    ridingTips: [
      'Wide open Plains terrain across most of the state rewards range and comfort over climbing torque',
      'The Ozark foothills in the northeast and the Wichita Mountains in the southwest are the two spots where extra torque genuinely pays off',
      'No statewide helmet law means it is a personal safety call more than a legal one here; wearing one is still the smart default at Class 3 speeds',
      'Summer heat across the Plains makes throttle-equipped Class 2 bikes popular for resting your legs mid-ride',
    ],
    topCities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
    metaDescription: 'Best electric bikes for Oklahoma. OK e-bike laws (no statewide helmet rule), top picks for Plains and foothill terrain, plus local dealers.',
    intro: 'Oklahoma is mostly wide, flat-to-rolling Plains, with real climbing only in the Ozark foothills to the northeast and the Wichita Mountains to the southwest. The state uses the standard three-class e-bike system with no license or registration requirement, and unlike most states, it has no statewide helmet law at any class or age.',
  },
  {
    slug: 'iowa',
    name: 'Iowa',
    abbreviation: 'IA',
    terrain: 'Rolling farmland and prairie across most of the state, with genuine hills in the unglaciated "Driftless Area" of the northeast corner.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No statewide requirement for Class 1 or Class 2. Class 3 riders are commonly expected to wear a helmet alongside the speedometer requirement.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'E-bikes are allowed on the state\'s extensive paved trail network under the same rules as bicycles, though some trail authorities can restrict Class 3 access.',
    lawSummary: 'Iowa adopted the federal three-class e-bike framework in 2021 through HF 493 (Iowa Code §321.235B). Class 1 and Class 3 are pedal-assist only, cutting off at 20 and 28 mph respectively; Class 2 allows throttle use up to 20 mph. Class 3 e-bikes must carry a working speedometer, and riders are typically expected to be 16 or older. No license, registration, or insurance is required for any class, and Iowa has never had a statewide bicycle helmet law outside the Class 3 expectation.',
    ridingTips: [
      'Iowa\'s famous RAGBRAI trail culture means a comfortable, long-range commuter or touring e-bike gets real use here',
      'Rolling farmland across most of the state is manageable on a mid-torque hub motor',
      'The Driftless Area in the northeast corner has real hills; budget more torque if that is where you ride',
      'Cold, snowy winters mean a bike with sealed battery contacts and good tire clearance for studded tires is worth considering',
    ],
    topCities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Iowa City', 'Dubuque'],
    metaDescription: 'Best electric bikes for Iowa. IA e-bike laws (three-class system since 2021), top picks for farmland and Driftless Area terrain, plus local dealers.',
    intro: 'Iowa is mostly rolling farmland and prairie, with the one genuinely hilly exception being the Driftless Area tucked into the northeast corner. The state adopted the standard three-class e-bike system in 2021, with no license or registration requirement, and its extensive paved trail network (including the RAGBRAI route) makes it a strong state for touring-style e-bikes.',
  },
  {
    slug: 'kansas',
    name: 'Kansas',
    abbreviation: 'KS',
    terrain: 'Flat to gently rolling Great Plains across most of the state, with the distinctive Flint Hills tallgrass prairie running through the east-central region.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No statewide helmet requirement for any age or class; any helmet rule is set at the municipal level.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Allowed anywhere bicycles are allowed, including bike lanes, multi-use paths, and trail networks, though cities and local authorities can restrict certain trails. Kansas state parks only permit e-bikes that stop assisting at 20 mph, which effectively excludes Class 3 from the state\'s marquee rail-trails.',
    lawSummary: 'Kansas adopted the three-class e-bike system in 2022 (KSA 8-1592b). Class 1 and Class 2 cut off at 20 mph, Class 3 at 28 mph, and Class 3 operators must be at least 16. No license, registration, insurance, or license plate is required for any class. There is no statewide helmet law at any age. A notable local wrinkle: Kansas Department of Wildlife and Parks policy caps state-park e-bike use at 20 mph, meaning Class 3 bikes are not permitted on the state\'s well-known rail-trail network even though they are legal on roads.',
    ridingTips: [
      'The flat-to-rolling Plains terrain across most of Kansas favors range over climbing torque',
      'If you plan to ride state-park rail-trails, a Class 1 or Class 2 bike is the safer buy since Class 3 is effectively excluded there',
      'The Flint Hills region has more relief than the rest of the state; a bit of extra torque helps on the steeper grades',
      'Persistent Plains wind is a bigger practical factor than hills for most Kansas riders; battery capacity matters more than motor power',
    ],
    topCities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe'],
    metaDescription: 'Best electric bikes for Kansas. KS e-bike laws (Class 3 excluded from state-park rail-trails), top picks for Plains and Flint Hills terrain, plus local dealers.',
    intro: 'Kansas is defined by wide, flat-to-rolling Great Plains, broken up by the tallgrass Flint Hills running through the east-central part of the state. It uses the standard three-class e-bike system adopted in 2022, with no statewide helmet law, but a distinctive local rule: state parks cap assisted speed at 20 mph, which keeps Class 3 bikes off the well-known rail-trail network.',
  },
  {
    slug: 'arkansas',
    name: 'Arkansas',
    abbreviation: 'AR',
    terrain: 'Mountainous Ozark and Ouachita terrain across the north and west, flat Mississippi Delta farmland in the east.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 21 on a Class 3 e-bike. No helmet requirement for Class 1 or Class 2.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 e-bikes are allowed on all state park trails designated for bicycle use, including mountain bike trails. Class 2 and Class 3 e-bikes are prohibited on those same mountain bike and multi-use trails in state parks.',
    lawSummary: 'Arkansas was an early adopter, passing its Electric Bicycle Act (Act 956 of 2017) to establish the standard three-class system. No license, registration, or insurance is required for any class. The state\'s helmet rule is unusually broad: anyone under 21, not just minors under 18, must wear a helmet to operate a Class 3 e-bike. State parks draw a sharper line than most states, allowing Class 1 on all designated bicycle and mountain bike trails while barring Class 2 and Class 3 from those same trails.',
    ridingTips: [
      'The Ozark and Ouachita mountains in the north and west reward a mid-drive motor with real climbing torque',
      'The flat Delta region in the east is a different world; range and comfort matter more than torque there',
      'If you are 18-20 and want a Class 3 e-bike, Arkansas\'s helmet rule still applies to you, higher than the under-18 threshold most states use',
      'Planning to ride state-park mountain bike trails: a Class 1 e-bike keeps every trail option open, since Class 2 and 3 are excluded from those same trails',
    ],
    topCities: ['Little Rock', 'Fayetteville', 'Bentonville', 'Fort Smith', 'Rogers'],
    metaDescription: 'Best electric bikes for Arkansas. AR e-bike laws (under-21 Class 3 helmet rule), top picks for Ozark mountain and Delta terrain, plus local dealers.',
    intro: 'Arkansas spans genuinely mountainous Ozark and Ouachita terrain in the north and west and flat Mississippi Delta farmland in the east, calling for very different bikes depending on where you ride. One of the earliest three-class adopters (2017), the state stands out for an unusually broad helmet rule: anyone under 21, not just minors, must wear one on a Class 3 e-bike.',
  },
];

export function getStateBySlug(slug: string): StateInfo | undefined {
  return STATES.find((s) => s.slug === slug);
}

export function getAllStateSlugs(): string[] {
  return STATES.map((s) => s.slug);
}
