export interface StateInfo {
  slug: string;
  name: string;
  abbreviation: string;
  terrain: string;
  classSystem: boolean;
  licenseRequired: boolean;
  helmetRequired: string;
  maxSpeed: string;
  maxWattage: string;
  bikePaths: string;
  lawSummary: string;
  ridingTips: string[];
  topCities: string[];
  metaDescription: string;
  intro: string;
}

export const STATES: StateInfo[] = [
  {
    slug: 'california',
    name: 'California',
    abbreviation: 'CA',
    terrain: 'Diverse: flat coastal cities, steep hills in San Francisco, mountain trails inland',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 18. Class 3 riders under 18 must wear a helmet.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on bike paths. Class 3 restricted to roads and bike lanes.',
    lawSummary: 'California was the first state to adopt the three-class e-bike system. As of 2026, all new e-bikes sold or rented must comply with UL 2849 safety certification. No license, registration, or insurance required. E-bikes must have a rear red reflector or taillight.',
    ridingTips: [
      'San Francisco hills demand a mid-drive motor with 60+ Nm torque',
      'Coastal fog and moisture mean fenders and integrated lights are essential',
      'Many California cities offer e-bike purchase rebates, so check local incentive programs before buying',
      'The California Coastal Trail offers hundreds of miles of scenic e-bike riding',
    ],
    topCities: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'Santa Monica'],
    metaDescription: 'Find the best electric bikes for riding in California. State e-bike laws, top picks for CA terrain, and where to buy.',
    intro: 'California leads the nation in e-bike adoption, with strong cycling infrastructure, purchase incentive programs, and year-round riding weather. Whether you are commuting through LA traffic, climbing San Francisco hills, or cruising the Pacific coast, there is an e-bike that fits.',
  },
  {
    slug: 'texas',
    name: 'Texas',
    abbreviation: 'TX',
    terrain: 'Mostly flat with gentle rolling hills. Hot summers make pedal-assist essential.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state helmet requirement for adults',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1, 2, and 3 allowed on roads. Local jurisdictions control bike path access.',
    lawSummary: 'Texas adopted the three-class system in 2019. E-bikes are treated as bicycles. No license, registration, or insurance required. Riders have the same rights and duties as cyclists. Local cities can set their own rules for trails and paths.',
    ridingTips: [
      'Texas heat makes throttle-equipped (Class 2) bikes popular so you can take a break from pedaling',
      'Flat terrain means you can prioritize range over torque',
      'Austin and San Antonio have expanding bike lane networks',
      'Hydration is critical for summer riding. Consider bikes with frame bag mounts for water bottles',
    ],
    topCities: ['Austin', 'Houston', 'Dallas', 'San Antonio', 'Fort Worth'],
    metaDescription: 'Best electric bikes for Texas riders. E-bike laws in TX, top picks for flat terrain and hot weather, plus local dealers.',
    intro: 'Texas offers thousands of miles of flat, open roads that are ideal for e-bike riding. The growing bike infrastructure in Austin, Houston, and Dallas makes commuting practical, and the warm climate means you can ride most of the year.',
  },
  {
    slug: 'new-york',
    name: 'New York',
    abbreviation: 'NY',
    terrain: 'Urban density in NYC, rolling hills upstate. Bridge crossings and multi-modal commuting.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 14. Class 3 riders of any age must wear a helmet in NYC.',
    maxSpeed: '25 mph (Class 3, NYC limit)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on most bike paths. Class 3 allowed in NYC bike lanes but not on greenways or sidewalks.',
    lawSummary: 'New York legalized e-bikes statewide in 2020. NYC has additional local rules: Class 3 e-bikes are capped at 25 mph (not 28), and throttle-only operation is limited. All classes are allowed on streets and in bike lanes. E-bikes are banned from sidewalks statewide.',
    ridingTips: [
      'Folding e-bikes are popular in NYC for apartment storage and subway/bus transfers',
      'The Brooklyn Bridge and Manhattan Bridge have dedicated bike lanes',
      'Invest in a quality U-lock; bike theft is a real concern in the city',
      'Upstate NY has beautiful rail-trail networks for recreational riding',
    ],
    topCities: ['New York City', 'Brooklyn', 'Buffalo', 'Albany', 'Rochester'],
    metaDescription: 'Best electric bikes for New York. NYC e-bike laws, top picks for city commuting and upstate trails, plus where to buy.',
    intro: 'New York City\'s Citi Bike e-bike usage jumped 65% recently, and for good reason. E-bikes turn a sweaty, exhausting city commute into something you actually look forward to. Whether you are navigating Manhattan traffic or exploring Hudson Valley trails, the right e-bike makes all the difference.',
  },
  {
    slug: 'florida',
    name: 'Florida',
    abbreviation: 'FL',
    terrain: 'Almost entirely flat. Coastal breezes can create headwinds. Year-round warm weather.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on bike paths unless locally restricted. Class 3 on roads and bike lanes.',
    lawSummary: 'Florida adopted the three-class system in 2020. E-bikes are classified as bicycles. No license, registration, or insurance required. Riders must be at least 16 years old to operate a Class 3 e-bike.',
    ridingTips: [
      'Flat terrain and warm weather make Florida ideal for e-bikes with maximum range',
      'Salt air along the coast accelerates corrosion, so look for bikes with rust-resistant components',
      'Afternoon thunderstorms are common in summer. Fenders and water-resistant displays are worth it',
      'Many beach communities have dedicated cycling paths perfect for cruiser-style e-bikes',
    ],
    topCities: ['Miami', 'Tampa', 'Orlando', 'Jacksonville', 'Fort Lauderdale'],
    metaDescription: 'Best electric bikes for Florida. FL e-bike laws, top picks for flat coastal riding, and where to find dealers near you.',
    intro: 'Florida\'s flat terrain, warm climate, and growing network of bike paths make it one of the best states for e-bike riding. The lack of hills means you can prioritize range and comfort over raw motor power, and you will ride comfortably year-round.',
  },
  {
    slug: 'washington',
    name: 'Washington',
    abbreviation: 'WA',
    terrain: 'Hilly west side (Seattle), flat eastern plains. Frequent rain in western WA.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for all riders in many counties and cities (including King County/Seattle)',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 allowed on all bike paths. Class 2 and 3 allowed where local authorities permit.',
    lawSummary: 'Washington uses the three-class system. E-bikes are treated as bicycles. No state license or registration required. Many local jurisdictions (including Seattle and King County) require helmets for all ages.',
    ridingTips: [
      'Seattle hills require solid torque. Look for 60+ Nm mid-drive motors',
      'Rain is a constant from October through May. Hydraulic disc brakes and fenders are non-negotiable',
      'The Burke-Gilman Trail is one of the best urban bike paths in the country',
      'Eastern Washington is flat and dry, which is a completely different riding experience',
    ],
    topCities: ['Seattle', 'Tacoma', 'Bellevue', 'Spokane', 'Olympia'],
    metaDescription: 'Best electric bikes for Washington state. WA e-bike laws, picks for Seattle hills and rainy weather, plus local dealers.',
    intro: 'Seattle has emerged as one of America\'s top e-bike cities, and the rest of Washington is catching up fast. The city\'s hills, reliable bike infrastructure, and rain-or-shine cycling culture make a capable e-bike the smartest transportation investment you can make.',
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    abbreviation: 'OR',
    terrain: 'Hilly and wet in Portland metro, mountainous east side. Strong cycling culture.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement (local rules may vary)',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '1000W',
    bikePaths: 'Class 1 and 2 allowed on bike paths. Class 3 on roads and bike lanes only.',
    lawSummary: 'Oregon allows e-bikes up to 1000W, which is higher than most states. The three-class system applies. No license or registration required. Portland has one of the most extensive bike lane networks in the US.',
    ridingTips: [
      'Portland is consistently ranked the most bike-friendly city in the US',
      'Oregon allows up to 1000W motors, giving you more options than most states',
      'The rain never really stops from fall through spring, so water resistance matters',
      'The Historic Columbia River Highway offers spectacular e-bike touring',
    ],
    topCities: ['Portland', 'Eugene', 'Salem', 'Bend', 'Corvallis'],
    metaDescription: 'Best electric bikes for Oregon. OR e-bike laws (up to 1000W allowed), top picks for Portland riding, and local dealers.',
    intro: 'Portland is the cycling capital of America, and Oregon\'s e-bike laws are among the most rider-friendly. The state allows motors up to 1000W (higher than the 750W limit in most states), and the infrastructure supports year-round commuting despite the rain.',
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    abbreviation: 'CO',
    terrain: 'High altitude, steep mountain terrain, and flat plains east of the Rockies.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement for adults',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 allowed on most multi-use paths. Class 3 restricted to roads. Some mountain trails open to Class 1 only.',
    lawSummary: 'Colorado uses the three-class system and was one of the early adopters. Local jurisdictions can open natural-surface trails to Class 1 e-bikes. No license or registration required. Boulder and Denver have strong cycling infrastructure.',
    ridingTips: [
      'Altitude matters: batteries drain faster at elevation, so plan for 10-20% less range above 5,000 ft',
      'Mountain terrain demands a mid-drive motor for efficient climbing',
      'Boulder has more bikes than cars on some routes, and the infrastructure reflects it',
      'Cold winters reduce battery capacity. Store your battery indoors when not riding',
    ],
    topCities: ['Denver', 'Boulder', 'Colorado Springs', 'Fort Collins', 'Aspen'],
    metaDescription: 'Best electric bikes for Colorado. CO e-bike laws, top picks for mountain terrain and high altitude, plus local dealers.',
    intro: 'Colorado\'s combination of mountain terrain, outdoor culture, and progressive cycling infrastructure makes it a natural fit for e-bikes. A strong motor is essential for the Rockies, and you will want to factor altitude into your battery range expectations.',
  },
  {
    slug: 'hawaii',
    name: 'Hawaii',
    abbreviation: 'HI',
    terrain: 'Volcanic hills, coastal roads, tropical climate. Short distances between towns.',
    classSystem: false,
    licenseRequired: true,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '20 mph',
    maxWattage: '750W',
    bikePaths: 'E-bikes allowed where bicycles are allowed, subject to local rules.',
    lawSummary: 'Hawaii has the highest e-bike search interest per capita in the US but has not adopted the three-class system. A valid driver\'s license is required. E-bikes are limited to 20 mph. Check individual island regulations, as county rules can vary.',
    ridingTips: [
      'Salt air and humidity accelerate corrosion, so stainless hardware and sealed electronics matter',
      'Short distances between towns mean you do not need a massive battery',
      'Trade winds can create strong headwinds on coastal roads',
      'Many tourist areas have e-bike rental shops if you want to try before buying',
    ],
    topCities: ['Honolulu', 'Maui', 'Kailua', 'Hilo', 'Kona'],
    metaDescription: 'Best electric bikes for Hawaii. HI e-bike regulations, top picks for island riding, and what to know before buying.',
    intro: 'Hawaii leads the nation in e-bike search interest per capita. The islands\' short distances, year-round warm weather, and scenic coastal roads make e-bikes a practical alternative to driving. Keep in mind that Hawaii has not adopted the standard three-class system, so the rules are a bit different here.',
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    abbreviation: 'AZ',
    terrain: 'Desert flat with some mountain terrain. Extreme summer heat.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on bike paths. Class 3 on roads and bike lanes.',
    lawSummary: 'Arizona adopted the three-class system. E-bikes are classified as bicycles. No license, registration, or insurance required. Riders under 18 on Class 3 bikes should check local helmet rules.',
    ridingTips: [
      'Summer temperatures regularly exceed 110F. Ride early morning or after sunset',
      'Flat desert terrain is ideal for long-range riding on lower assist levels',
      'Scottsdale and Tempe have excellent cycling infrastructure',
      'UV exposure degrades rubber and plastic over time. Store your e-bike out of direct sun',
    ],
    topCities: ['Phoenix', 'Scottsdale', 'Tucson', 'Tempe', 'Mesa'],
    metaDescription: 'Best electric bikes for Arizona. AZ e-bike laws, top picks for desert riding and extreme heat, plus local dealers.',
    intro: 'Arizona\'s flat desert terrain and 300+ days of sunshine make it ideal for e-bike riding, as long as you respect the summer heat. The state\'s cities are investing heavily in cycling infrastructure, and the lack of hills means your battery goes further.',
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    abbreviation: 'IL',
    terrain: 'Flat to gently rolling. Cold winters, warm summers. Chicago is a major cycling city.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement (recommended)',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on multi-use paths. Class 3 on roads.',
    lawSummary: 'Illinois uses the three-class system. No license or registration required. Chicago has one of the largest bike-share systems in the country (Divvy), and nearly half of Divvy rides are now on e-bikes.',
    ridingTips: [
      'Chicago cycling is up 119% over four years, driven largely by e-bikes',
      'The Lakefront Trail is 18 miles of car-free riding along Lake Michigan',
      'Winter riding is viable with the right gear but expect 15-25% less battery range in cold weather',
      'Flat terrain means virtually any e-bike will handle the geography well',
    ],
    topCities: ['Chicago', 'Evanston', 'Naperville', 'Springfield', 'Champaign'],
    metaDescription: 'Best electric bikes for Illinois. IL e-bike laws, top picks for Chicago commuting, and where to buy near you.',
    intro: 'Chicago has become one of America\'s biggest e-bike success stories, with cycling numbers up over 100% in recent years. Nearly half of all bike-share rides in the city are now on e-bikes. The flat terrain and expanding bike lane network make the whole state accessible on two wheels.',
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    abbreviation: 'NC',
    terrain: 'Mountains in the west, piedmont rolling hills, flat coastal plain east.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on bike paths. Class 3 on roads.',
    lawSummary: 'North Carolina adopted the three-class system. E-bikes are treated as bicycles. No license or registration required. The Blue Ridge Parkway has specific rules for e-bikes on certain sections.',
    ridingTips: [
      'Western NC mountains are serious climbing territory. A mid-drive motor is highly recommended',
      'The Triangle area (Raleigh-Durham-Chapel Hill) has strong cycling infrastructure',
      'Humidity and summer heat make throttle-assist popular for taking breaks from pedaling',
      'The Outer Banks has scenic but windy coastal riding',
    ],
    topCities: ['Charlotte', 'Raleigh', 'Asheville', 'Durham', 'Wilmington'],
    metaDescription: 'Best electric bikes for North Carolina. NC e-bike laws, picks for mountain and coastal terrain, plus local dealers.',
    intro: 'North Carolina offers some of the most diverse riding terrain in the US, from the Blue Ridge Mountains to the Outer Banks coastline. The growing cycling infrastructure in Charlotte and the Triangle makes commuting viable, while the mountains offer world-class recreational riding.',
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    abbreviation: 'VA',
    terrain: 'Rolling hills, Appalachian mountains in the west, flat tidewater region east.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 14',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 on all bike paths. Class 2 and 3 where locally permitted.',
    lawSummary: 'Virginia uses the three-class system. E-bikes are classified as bicycles. No license or registration required. Northern Virginia benefits from DC-area bike infrastructure. Virginia Beach and Richmond have growing cycling networks.',
    ridingTips: [
      'Northern Virginia connects to the extensive DC bike path network',
      'The Virginia Creeper Trail is one of the most popular rail-trails in the country',
      'Four distinct seasons mean you will deal with heat, cold, and rain throughout the year',
      'Richmond has become an underrated cycling city with improving infrastructure',
    ],
    topCities: ['Arlington', 'Richmond', 'Virginia Beach', 'Alexandria', 'Norfolk'],
    metaDescription: 'Best electric bikes for Virginia. VA e-bike laws, top picks for DC-area commuting and trail riding, plus dealers.',
    intro: 'Virginia\'s location between the Appalachian Mountains and the Atlantic coast gives riders diverse terrain, and the northern part of the state connects directly to DC\'s excellent cycling infrastructure. Whether you commute into the capital or explore the Virginia Creeper Trail, the right e-bike opens up the state.',
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    abbreviation: 'GA',
    terrain: 'Rolling hills in Atlanta, flat coastal plain toward Savannah. Hot, humid summers.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16',
    maxSpeed: '20 mph (Class 1 and 2), 28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 allowed on multi-use paths. Class 2 and 3 on roads and bike lanes.',
    lawSummary: 'Georgia adopted the three-class system. E-bikes are classified as bicycles. No license or registration required. Atlanta has been expanding its BeltLine trail network, which is a major cycling corridor.',
    ridingTips: [
      'Atlanta\'s BeltLine is a 22-mile loop of trails connecting 45 neighborhoods',
      'Summer humidity is intense. A throttle lets you take pedaling breaks without stopping',
      'The rolling hills around Atlanta benefit from a motor with decent torque',
      'Savannah\'s flat, compact layout is perfect for casual e-bike cruising',
    ],
    topCities: ['Atlanta', 'Savannah', 'Athens', 'Augusta', 'Decatur'],
    metaDescription: 'Best electric bikes for Georgia. GA e-bike laws, top picks for Atlanta commuting and Savannah cruising, plus dealers.',
    intro: 'Atlanta\'s expanding BeltLine trail network is turning the city into a cycling destination, and e-bikes make the rolling hills manageable for daily commuting. The combination of warm weather, growing infrastructure, and a car-heavy city desperate for alternatives makes Georgia a strong e-bike market.',
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    abbreviation: 'MA',
    terrain: 'Hilly in the west, rolling terrain around Boston. Cold winters.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 16. Recommended for all ages.',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 on all paths. Class 2 where locally permitted. Class 3 on roads.',
    lawSummary: 'Massachusetts updated its e-bike laws in recent years to adopt the three-class system. E-bikes are treated as bicycles. No license or registration required. Boston has an expanding protected bike lane network.',
    ridingTips: [
      'Boston has notoriously narrow streets, so a compact or folding e-bike is practical',
      'The Minuteman Bikeway and Cape Cod Rail Trail are excellent recreational rides',
      'Winter riding is feasible but battery range drops significantly below freezing',
      'Cambridge and Somerville have some of the best cycling infrastructure in the state',
    ],
    topCities: ['Boston', 'Cambridge', 'Somerville', 'Worcester', 'Salem'],
    metaDescription: 'Best electric bikes for Massachusetts. MA e-bike laws, picks for Boston commuting and Cape Cod trails, plus dealers.',
    intro: 'Boston\'s dense urban core and limited parking make e-bikes a genuinely practical commuting option. The combination of expanding protected bike lanes, excellent rail-trail networks, and a compact metro area means many Bostonians can replace car trips entirely with an e-bike.',
  },
  {
    slug: 'utah',
    name: 'Utah',
    abbreviation: 'UT',
    terrain: 'Mountain terrain, high desert, dramatic elevation changes. Four distinct seasons.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 on bike paths and some natural-surface trails. Class 2 and 3 on roads.',
    lawSummary: 'Utah uses the three-class system. E-bikes are treated as bicycles. No license or registration required. Some national parks and BLM land in Utah allow Class 1 e-bikes on trails where traditional bikes are permitted.',
    ridingTips: [
      'Utah has the third-highest e-bike interest in the US per capita',
      'High altitude (4,000-6,000 ft in the valleys) reduces battery range by 10-15%',
      'Salt Lake City\'s grid layout and flat valley floor make it great for commuting',
      'Moab and Park City offer world-class trail riding on Class 1 e-bikes',
    ],
    topCities: ['Salt Lake City', 'Provo', 'Park City', 'Moab', 'Ogden'],
    metaDescription: 'Best electric bikes for Utah. UT e-bike laws, top picks for mountain terrain and trail riding, plus where to buy.',
    intro: 'Utah ranks third in the nation for e-bike interest per capita, and it is easy to see why. The state offers everything from flat Salt Lake City commuting to epic Moab trail riding. Altitude is a factor here, so plan for reduced battery range in the mountain valleys.',
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    abbreviation: 'MI',
    terrain: 'Generally flat to gently rolling. Cold winters, pleasant summers. Extensive lakefront.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on bike paths. Class 3 on roads.',
    lawSummary: 'Michigan uses the three-class system. E-bikes are treated as bicycles. No license or registration required. The state has been investing in cycling infrastructure, particularly in the Detroit metro and Grand Rapids areas.',
    ridingTips: [
      'Michigan has over 2,600 miles of rail trails, more than almost any other state',
      'Lakefront riding is beautiful but windy. A headwind eats battery fast',
      'Winter riding is possible but limited. Store your battery indoors between rides',
      'Mackinac Island bans motorized vehicles but allows Class 1 e-bikes on some paths',
    ],
    topCities: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Traverse City', 'Lansing'],
    metaDescription: 'Best electric bikes for Michigan. MI e-bike laws, top picks for rail-trail riding and lakefront commuting, plus dealers.',
    intro: 'Michigan has over 2,600 miles of rail trails and a growing cycling culture in cities like Grand Rapids and Ann Arbor. The flat terrain is forgiving for any motor type, and the extensive trail network makes recreational riding a year-round attraction (at least from April through November).',
  },
  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    abbreviation: 'PA',
    terrain: 'Hilly, especially in Pittsburgh. Philadelphia is relatively flat. Rural mountain areas.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'Required for riders under 12',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '750W',
    bikePaths: 'Class 1 and 2 on bike paths. Class 3 on roads. Some rail-trails allow e-bikes.',
    lawSummary: 'Pennsylvania adopted the three-class e-bike system. E-bikes are classified as pedalcycles. No license or registration required. The state has an extensive network of rail-trails, with some allowing e-bikes.',
    ridingTips: [
      'Pittsburgh\'s hills are no joke. If you commute there, get a mid-drive with at least 60 Nm',
      'Philadelphia is relatively flat and has a growing protected bike lane network',
      'The Great Allegheny Passage (150 miles) is one of the best long-distance bike trails in the US',
      'Pennsylvania has four seasons. Expect cold winters and hot, humid summers',
    ],
    topCities: ['Philadelphia', 'Pittsburgh', 'State College', 'Harrisburg', 'Lancaster'],
    metaDescription: 'Best electric bikes for Pennsylvania. PA e-bike laws, picks for Philadelphia commuting and Pittsburgh hills, plus dealers.',
    intro: 'Pennsylvania offers two very different riding experiences: flat Philadelphia with its expanding bike lane network, and hilly Pittsburgh where a powerful motor turns impossible commutes into pleasant rides. The state also has incredible rail-trail riding, including the 150-mile Great Allegheny Passage.',
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    abbreviation: 'NJ',
    terrain: 'Mostly flat with some rolling hills. Dense urban areas, beach communities.',
    classSystem: false,
    licenseRequired: true,
    helmetRequired: 'Required for riders under 17',
    maxSpeed: '20 mph',
    maxWattage: '750W',
    bikePaths: 'E-bikes allowed where bicycles are allowed, subject to local rules.',
    lawSummary: 'In 2026, New Jersey eliminated the three-class system and reclassified all e-bikes as "motorized bicycles." A valid driver\'s license is required. E-bikes are limited to 20 mph motor-assisted speed. Rules may differ from neighboring states, so check current regulations.',
    ridingTips: [
      'New Jersey\'s 2026 law change means your rules differ from neighboring NY and PA, so pay attention at state borders',
      'The Jersey Shore has excellent boardwalk and coastal riding',
      'Dense urban areas in northern NJ benefit from folding e-bikes for train commuters',
      'The D&R Canal towpath offers 70+ miles of flat, scenic riding',
    ],
    topCities: ['Jersey City', 'Newark', 'Hoboken', 'Princeton', 'Asbury Park'],
    metaDescription: 'Best electric bikes for New Jersey. NJ e-bike regulations (updated 2026), top picks for Shore riding and commuting.',
    intro: 'New Jersey made a significant regulatory change in 2026 by eliminating the three-class system and reclassifying e-bikes as "motorized bicycles." This means you need a valid driver\'s license to ride one. Despite the stricter rules, e-bikes remain popular for Shore riding, urban commuting, and canal trail exploring.',
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    abbreviation: 'MN',
    terrain: 'Flat to gently rolling. Harsh winters, pleasant summers. Lake country.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '28 mph (Class 3)',
    maxWattage: '1000W',
    bikePaths: 'Class 1 and 2 on state trails. Class 3 on roads. Some trails allow all classes.',
    lawSummary: 'Minnesota allows e-bikes up to 1000W, one of the highest limits in the nation. The three-class system applies. No license or registration required. Minneapolis has been ranked among the top bike-friendly cities in the US.',
    ridingTips: [
      'Minnesota allows 1000W motors, giving you more power options than most states',
      'Minneapolis has over 200 miles of on- and off-street bikeways',
      'Winter riding is a real thing here. Fat-tire e-bikes are popular for snow riding',
      'The Midtown Greenway is a car-free commuting corridor through Minneapolis',
    ],
    topCities: ['Minneapolis', 'St. Paul', 'Duluth', 'Rochester', 'Bloomington'],
    metaDescription: 'Best electric bikes for Minnesota. MN e-bike laws (up to 1000W allowed), top picks for Minneapolis commuting and winter riding.',
    intro: 'Minneapolis consistently ranks among America\'s most bike-friendly cities, with over 200 miles of bikeways and a culture that rides year-round. Minnesota also allows motors up to 1000W (higher than most states), giving you extra power for headwinds and winter conditions.',
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    abbreviation: 'OH',
    terrain: 'Flat in the northwest, rolling hills in the southeast. Four-season climate.',
    classSystem: true,
    licenseRequired: false,
    helmetRequired: 'No state requirement',
    maxSpeed: '20 mph (motor-assisted)',
    maxWattage: '750W',
    bikePaths: 'E-bikes allowed on most multi-use paths. Local jurisdictions may restrict.',
    lawSummary: 'Ohio classifies e-bikes as bicycles with a 20 mph motor-assisted speed limit and 750W maximum. No license or registration required. The state has extensive rail-trail networks and growing urban cycling infrastructure.',
    ridingTips: [
      'Ohio has over 1,800 miles of multi-use trails, perfect for e-bike exploring',
      'Columbus has invested heavily in cycling infrastructure in recent years',
      'The Ohio to Erie Trail runs 326 miles from Cleveland to Cincinnati',
      'Budget-friendly e-bikes perform well on Ohio\'s mostly flat terrain',
    ],
    topCities: ['Columbus', 'Cleveland', 'Cincinnati', 'Dayton', 'Toledo'],
    metaDescription: 'Best electric bikes for Ohio. OH e-bike laws, top picks for trail riding and city commuting, plus local dealers.',
    intro: 'Ohio\'s flat terrain and extensive trail network (over 1,800 miles of multi-use trails) make it an underrated e-bike state. The Ohio to Erie Trail alone stretches 326 miles from Cleveland to Cincinnati. Cities like Columbus are investing in cycling infrastructure, making daily commuting increasingly practical.',
  },
];

export function getStateBySlug(slug: string): StateInfo | undefined {
  return STATES.find((s) => s.slug === slug);
}

export function getAllStateSlugs(): string[] {
  return STATES.map((s) => s.slug);
}
